### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by AlexKucera** [sebsel/kirby-micropub#14]
Hi,

I tried to install the Micropub plugin and run the https://micropub.rocks test suite on it. Discovery of the endpoint works and everything looks peachy. But then when running the actual tests nothing works. I always get an error 500:

```
HTTP/1.1 500 Internal Server Error
Date: Thu, 29 Jun 2017 12:46:31 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=xxx; expires=Fri, 29-Jun-18 12:46:31 GMT; path=/; domain=.alexanderkucera.com; HttpOnly
Vary: Accept-Encoding
Server: cloudflare-nginx
CF-RAY: 3768fd3612305134-SJC

{
    "error": "error",
    "error_description": "Non-static method IndieWeb\\IndieAuth::requireMe() should not be called statically, assuming $this from incompatible context"
}
```

Any idea what might be wrong?

**Comment by sebsel** [comment]
Hmm. I'm actually using one of the branches myself at the moment, not the master branch. I should put a warning up that it isn't really a great and working plugin at the moment.

I am planning on redoing the whole thing, so it can be used again.

This is indeed a thing I fixed in the update query branch and I should fix it in the master too. (fix is here: https://github.com/sebsel/kirby-micropub/commit/4fa6e401e8b231842cca556e5f92f1e95f761c15)

**Comment by sebsel** [comment]
I merged my update-query branch into master, for I am using that one myself, so I think it has the least bugs. And I added a warning ;) Hope you will pass some tests now, it should pass some.

Redoing the thing so that it's more flexible is on my list!

**Comment by AlexKucera** [comment]
cheers. I'll give it a try.

**Comment by AlexKucera** [comment]
Hi Sebastian,

the updates definitely changed things. Now I get a different error. :)

It looks like the auth token does not get sent properly now.

The POST request does include it though (not the real on below. I changed it slightly):

```
POST http://blog.alexanderkucera.com/micropub HTTP/1.1
Authorization: Bearer xxx
Content-type: application/json

{
  "type": ["h-entry"],
  "properties": {
    "content": ["Micropub test of creating an h-entry with a JSON request"]
  }
}
```

```
HTTP/1.1 200 OK
Date: Thu, 29 Jun 2017 21:06:33 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=d8e56869c15f9d5586a1ddda9dff78744f11498770393; expires=Fri, 29-Jun-18 21:06:33 GMT; path=/; domain=.alexanderkucera.com; HttpOnly
Vary: Accept-Encoding
Server: cloudflare-nginx
CF-RAY: 376bd9ad45af6c22-SJC

An access token is required. Send an HTTP Authorization header such as 'Authorization: Bearer xxx' or include a POST-body parameter such as 'access_token=xxx'
```

**Comment by sebsel** [comment]
Hm, that's weird.

First off: please do not publish whatever follows `Authorization: Bearer` on a public place. That eyJ0eX-thing is your access token and gives people who use it access to your Micropub endpoint. The tokens issued by https://tokens.indieauth.com/token (which the plugin defaults to) are hard to revoke. I believe I don't even let them expire in the code now, which I should fix. But treat strings like that as your password :) I've edited your comment to make it `xxx`, but it might not be fully gone yet.

***

Then your problem: even with `xxx` in that context, it should at least say that you have an invalid token, not that you miss one. Since your request has one, I think your server is not setting the `$_SERVER['HTTP_AUTHORIZATION']` for PHP. This is a default on some servers (I had it on my 
local dev server). I added `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1` to my Apache config file and that solved it. You can try and do `var_dump($_SERVER['HTTP_AUTHORIZATION']);` to see if it's set.

**Comment by AlexKucera** [comment]
No worries Sebastian. I edited the token before posting. It was useless. Just a few random characters added here and there. 

I'll try the dump. Not sure how, but I'll figure that out. Thanks for your help.

**Comment by sebsel** [comment]
Hi Alex, I see you did indeed, but I still would urge you not to publish such things, because you just give away too much information :)

Tokens issued by IndieAuth are JWT, which means you can easily base64_decode them. The first part (until the first dot) is always base64 encoded `{"typ":"JWT","alg":"HS256"}`, the next part is a base64 encoded JSON with information about you, which is also not really secret, and only the last part is a signed token, verifying the token. Since you did not add any new characters to that part of your access token (I found it in my e-mail still), I only had to restore the first part (which is always the same) and the middle part (which is easy when you see the json and know what to expect). I had it open in a whim.

That said, I will now work on a way to revoke access tokens issued before a certain date, in your case 1498770106 or 2017-06-29 21:01:46 ;)

![schermafbeelding 2017-06-30 om 15 31 57](https://user-images.githubusercontent.com/16517999/27737702-725a8414-5da9-11e7-9abd-cecc96fc23a9.jpg)

**Comment by AlexKucera** [comment]
haha. point taken. :)

**Comment by AlexKucera** [comment]
Ok, so the var_dump gives me `NULL`, which I assume means the variable is not set. Any ideas how to make that work on a shared host?

**Comment by AlexKucera** [comment]
Ok. It works.

Adding `SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`to my .htaccess file did it. I just didn't understand that is what you were referring to with the Apache config file.

Thanks again for your patience and help Sebastian.

Now I just need to fiddle with the configuration settings to get the page format as I need it. (I use a different data style mainly (YYYY-DD-MM-HH-mm-SS) and a fixed title.)
